function output = importfile_bridge(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GTBRIDGECRANEDATAIMPULSE1100 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  GTBRIDGECRANEDATAIMPULSE1100 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  GTBridgeCraneDataimpulse1100 = importfile("E:\Google Drive\Georgia Tech\2020 Fall\ME 6404 - Adv Control Design Implementation\ME 6404 Lab\Lab 6 - Final Project\Matlab Code\RLS\Data\GT_BridgeCrane_Data_impulse_1100.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12:21:56.2156

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimeXdirsec", "XPayloadDeflectionmm", "XCranePositionmm", "XActualVelocitymmsec", "XCommandVelocitymmsec", "XDeflectionErrormm", "TimeYdirsec", "YPayloadDeflectionmm", "YCranePositionmm", "YActualVelocitymmsec", "YCommandVelocitymmsec", "YDeflectionErrormm"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
output = readtable(filename, opts);

toDelete = output.TimeYdirsec == 0; 
output(toDelete, :) = []; 

end